batch_type: numel
batch_bins: 32000000
accum_grad: 1
max_epoch: 20
patience: 100
# The initialization method for model parameters
init: chainer
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: rnn
encoder_conf:
    rnn_type: lstm
    bidirectional: true
    use_projection: false
    num_layers: 2
    hidden_size: 512
    output_size: 512

decoder: rnn
decoder_conf:
    rnn_type: lstm
    num_layers: 2
    hidden_size: 512
    sampling_probability: 0.0
    att_conf:
        atype: location
        adim: 512
        awin: 5
        aheads: 1
        aconv_chans: 10
        aconv_filts: 100

model_conf:
    length_normalized_loss: false
    lsm_weight: 0.1

optim: adadelta
optim_conf:
    lr: 1.0
    rho: 0.95
    eps: 1.0e-08
    weight_decay: 0

#specaug: specaug
#specaug_conf:
#    apply_time_warp: false
#    time_warp_window: 5
#    time_warp_mode: bicubic
#    apply_freq_mask: false
#    freq_mask_width_range:
#    - 0
#    - 30
#    num_freq_mask: 2
#    apply_time_mask: true
#    time_mask_width_range:
#    - 0
#    - 3
#    num_time_mask: 6
