accum_grad: 1
optim: adam
max_epoch: 100
batch_size: 200
optim_conf:
    lr: 0.001
    weight_decay: 0
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 1