dataset: cifar10
in_ch: 3
out_ch: 10

accum_grad: 1
max_epoch: 100
batch_size: 50

best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

scheduler: steplr
scheduler_conf:
    step_size: 20
    gamma: 0.2

optim: sgd
optim_conf:
    lr: 0.1
    weight_decay: 0.0005
    momentum: 0.9

xai_excute: 1
xai_mode: bg
st_excute: 0

bias: 0
batch_norm: 0
cfg_type: D

