accum_grad: 10
optim: adam
max_epoch: 200
batch_size: 20
optim_conf:
    lr: 0.001
    weight_decay: 0
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 1