accum_grad: 1
optim: adam
max_epoch: 101
batch_size: 50
optim_conf:
    lr: 0.0001
    weight_decay: 0.0001
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 1
xai_excute: 1
xai_mode: ig
cfg_type: B4
bias: 0
st_excute: 0