accum_grad: 1
max_epoch: 100
batch_size: 50

best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

scheduler: steplr
scheduler_conf:
    step_size: 60
    gamma: 0.1

optim: adam
optim_conf:
    lr: 0.0001
    weight_decay: 0.0001

xai_excute: 1
xai_mode: bg
st_excute: 0

bias: 0
cfg_type: B0

