accum_grad: 6
optim: adam
max_epoch: 2000
batch_size: 35
optim_conf:
    lr: 0.001
    weight_decay: 0
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 1