optim: sgd
init: xavier_uniform
max_epoch: 25
batch_size: 300
optim_conf:
    lr: 0.001
    weight_decay: 0
patience: 4
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 1
# scheduler: reducelronplateau
# scheduler_conf:
#     mode: min
#     factor: 0.5
#     patience: 1