accum_grad: 1
optim: adam
max_epoch: 100
batch_size: 50
optim_conf:
    lr: 0.0001
    weight_decay: 0.0001
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 1
xai_excute: 1
xai_mode: bg
cfg_type: D
bias: 0
st_excute: 1