# This configuration requires 1 gpu
accum-grad: 4
adim: 256
aheads: 4
backend: pytorch
batch-size: 256
dropout-rate: 0.3
elayers: 6
epochs: 200
eunits: 1024
grad-clip: 5
lsm-weight: 0.1
model-module: moneynet.nets.pytorch_backend.e2e_asr_transformer:E2E
mtlalpha: 0.0
opt: noam
patience: 0
sortagrad: 0
transformer-attn-dropout-rate: 0.1
transformer-init: pytorch
transformer-input-layer: conv2d
transformer-length-normalized-loss: false
transformer-lr: 100.0
transformer-warmup-steps: 25000
oversampling: 4
outer : 1
residual: 0
