# Note: run this config with "--feats_normalize null"
batch_type: numel
batch_bins: 6000000
accum_grad: 1
max_epoch: 100
patience: none
# The initialization method for model parameters
init: chainer
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 3

input_size: 2048
encoder: wav2vec2
encoder_conf:
    output_size: 512
    normalize_before: true
    freeze_w2v: false
    w2v_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/libri960_big.pt
    w2v_dir_path: ./data/
    finetune_last_n_layers: 1

decoder: rnn
decoder_conf:
    rnn_type: lstm
    num_layers: 2
    hidden_size: 1024
    sampling_probability: 0.0
    att_conf:
        atype: location
        adim: 1024
        awin: 5
        aheads: 2
        aconv_chans: 10
        aconv_filts: 100

model_conf:
    ctc_weight: 0.5
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adadelta
optim_conf:
    lr: 1.0
    rho: 0.95
    eps: 1.0e-08
    weight_decay: 0

unused_parameters: true

frontend: null

normalize: null

specaug: null
