batch_type: numel
batch_bins: 20000000
accum_grad: 1
max_epoch: 80
patience: 100
# The initialization method for model parameters
init: chainer
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: wav2vec2
encoder_conf:
    input_size: 1
    w2v_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_small.pt

decoder: rnn
decoder_conf:
    rnn_type: lstm
    num_layers: 2
    hidden_size: 1024
    sampling_probability: 0.0
    att_conf:
        atype: location
        adim: 1024
        awin: 5
        aheads: 1
        aconv_chans: 10
        aconv_filts: 100

model_conf:
    ctc_weight: 0.5
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adadelta
optim_conf:
    lr: 1.0
    rho: 0.95
    eps: 1.0e-08
    weight_decay: 0

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
