# model name for training
model-module: "moneynet.nets.pytorch_backend.ar_unsup_gate:NetTransform"

# minibatch related
accum-grad: 8
batch-bins: 100000

# optimization related
opt: adam
grad-clip: 1
lr: 0.001

# scheduling related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
epochs: 40

# model architecture
tnum: 1
hdim: 320
brewing: 1