# model name for training
model-module: "moneynet.nets.pytorch_backend.ar_unsup_simnn:Net"

# minibatch related
accum-grad: 4
batch-bins: 110000

# optimization related
opt: sgd
grad-clip: 5

# scheduling related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
epochs: 10

# model architecture
etype: linear
hdim: 480
cdim: 160
tnum: 2