# model name for training
model-module: "moneynet.nets.pytorch_backend.ar_unsup_deq:NetTransform"

# minibatch related
accum-grad: 4
batch-bins: 8000000

# optimization related
# opt: adadelta
# grad-clip: 5

opt: adam
grad-clip: 1
lr: 0.001

#opt: noam
#lr: 10.0
#warmup-steps: 25000
#grad-clip: 5

# scheduling related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
epochs: 30
# model architecture
tnum: 0
hdim: 512