# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KT_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_KT(object):
    def setupUi(self, KT):
        KT.setObjectName("KT")
        KT.resize(783, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(KT.sizePolicy().hasHeightForWidth())
        KT.setSizePolicy(sizePolicy)
        KT.setStyleSheet("background-color: rgb(47,48,51)")
        self.centralwidget = QtWidgets.QWidget(KT)
        self.centralwidget.setStyleSheet("background-color: rgb(47,48,51);\n"
"font: 10pt \"Malgun Gothic\";s")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Widget = QtWidgets.QWidget(self.centralwidget)
        self.Top_Widget.setStyleSheet("background-color: rgb(191,191,191);\n"
"font: 10pt \"Malgun Gothic\";")
        self.Top_Widget.setObjectName("Top_Widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.Top_Widget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.TopLeft_Widget = QtWidgets.QWidget(self.Top_Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopLeft_Widget.sizePolicy().hasHeightForWidth())
        self.TopLeft_Widget.setSizePolicy(sizePolicy)
        self.TopLeft_Widget.setMinimumSize(QtCore.QSize(590, 0))
        self.TopLeft_Widget.setStyleSheet("")
        self.TopLeft_Widget.setObjectName("TopLeft_Widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.TopLeft_Widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Original_Script = QtWidgets.QLabel(self.TopLeft_Widget)
        self.Original_Script.setMinimumSize(QtCore.QSize(572, 74))
        self.Original_Script.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.Original_Script.setAlignment(QtCore.Qt.AlignCenter)
        self.Original_Script.setObjectName("Original_Script")
        self.verticalLayout_2.addWidget(self.Original_Script)
        self.Kaldi_Script = QtWidgets.QLabel(self.TopLeft_Widget)
        self.Kaldi_Script.setMinimumSize(QtCore.QSize(572, 74))
        self.Kaldi_Script.setToolTipDuration(-1)
        self.Kaldi_Script.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.Kaldi_Script.setAlignment(QtCore.Qt.AlignCenter)
        self.Kaldi_Script.setObjectName("Kaldi_Script")
        self.verticalLayout_2.addWidget(self.Kaldi_Script)
        self.E2E_Script = QtWidgets.QLabel(self.TopLeft_Widget)
        self.E2E_Script.setMinimumSize(QtCore.QSize(572, 74))
        self.E2E_Script.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.E2E_Script.setAlignment(QtCore.Qt.AlignCenter)
        self.E2E_Script.setObjectName("E2E_Script")
        self.verticalLayout_2.addWidget(self.E2E_Script)
        self.horizontalLayout_9.addWidget(self.TopLeft_Widget)
        self.TopRight_Widget = QtWidgets.QWidget(self.Top_Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopRight_Widget.sizePolicy().hasHeightForWidth())
        self.TopRight_Widget.setSizePolicy(sizePolicy)
        self.TopRight_Widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TopRight_Widget.setStyleSheet("")
        self.TopRight_Widget.setObjectName("TopRight_Widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.TopRight_Widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.TopRight_Widget)
        self.widget_4.setMinimumSize(QtCore.QSize(50, 0))
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.WER_Label = QtWidgets.QLabel(self.widget_4)
        self.WER_Label.setMinimumSize(QtCore.QSize(55, 56))
        self.WER_Label.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.WER_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.WER_Label.setObjectName("WER_Label")
        self.horizontalLayout_3.addWidget(self.WER_Label)
        self.CER_Label = QtWidgets.QLabel(self.widget_4)
        self.CER_Label.setMinimumSize(QtCore.QSize(55, 56))
        self.CER_Label.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.CER_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.CER_Label.setObjectName("CER_Label")
        self.horizontalLayout_3.addWidget(self.CER_Label)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.widget_6 = QtWidgets.QWidget(self.TopRight_Widget)
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Kaldi_WER = QtWidgets.QLabel(self.widget_6)
        self.Kaldi_WER.setMinimumSize(QtCore.QSize(55, 56))
        self.Kaldi_WER.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.Kaldi_WER.setAlignment(QtCore.Qt.AlignCenter)
        self.Kaldi_WER.setObjectName("Kaldi_WER")
        self.horizontalLayout_4.addWidget(self.Kaldi_WER)
        self.Kaldi_CER = QtWidgets.QLabel(self.widget_6)
        self.Kaldi_CER.setMinimumSize(QtCore.QSize(55, 56))
        self.Kaldi_CER.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.Kaldi_CER.setAlignment(QtCore.Qt.AlignCenter)
        self.Kaldi_CER.setObjectName("Kaldi_CER")
        self.horizontalLayout_4.addWidget(self.Kaldi_CER)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.TopRight_Widget)
        self.widget_7.setStyleSheet("")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.E2E_WER = QtWidgets.QLabel(self.widget_7)
        self.E2E_WER.setMinimumSize(QtCore.QSize(55, 56))
        self.E2E_WER.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.E2E_WER.setAlignment(QtCore.Qt.AlignCenter)
        self.E2E_WER.setObjectName("E2E_WER")
        self.horizontalLayout_5.addWidget(self.E2E_WER)
        self.E2E_CER = QtWidgets.QLabel(self.widget_7)
        self.E2E_CER.setMinimumSize(QtCore.QSize(55, 56))
        self.E2E_CER.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.E2E_CER.setAlignment(QtCore.Qt.AlignCenter)
        self.E2E_CER.setObjectName("E2E_CER")
        self.horizontalLayout_5.addWidget(self.E2E_CER)
        self.verticalLayout_3.addWidget(self.widget_7)
        self.horizontalLayout_9.addWidget(self.TopRight_Widget)
        self.verticalLayout.addWidget(self.Top_Widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bottom_Widget = QtWidgets.QWidget(self.centralwidget)
        self.bottom_Widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bottom_Widget.setStyleSheet("background-color: rgb(191,191,191);\n"
"font: 10pt \"Malgun Gothic\";")
        self.bottom_Widget.setObjectName("bottom_Widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.bottom_Widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_9 = QtWidgets.QWidget(self.bottom_Widget)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.FileName_label = QtWidgets.QLabel(self.widget_9)
        self.FileName_label.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.FileName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.FileName_label.setObjectName("FileName_label")
        self.verticalLayout_6.addWidget(self.FileName_label)
        self.Wav_Widget = QtWidgets.QWidget(self.widget_9)
        self.Wav_Widget.setMinimumSize(QtCore.QSize(500, 200))
        self.Wav_Widget.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.Wav_Widget.setObjectName("Wav_Widget")
        self.verticalLayout_6.addWidget(self.Wav_Widget)
        self.horizontalLayout_6.addWidget(self.widget_9)
        self.widget_2 = QtWidgets.QWidget(self.bottom_Widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        self.widget_8.setMaximumSize(QtCore.QSize(50, 70))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.play_button = QtWidgets.QPushButton(self.widget_8)
        self.play_button.setStyleSheet("image: url(./Pictures/play.png);\n"
"border: 0px;")
        self.play_button.setText("")
        self.play_button.setObjectName("play_button")
        self.verticalLayout_5.addWidget(self.play_button)
        self.stop_button = QtWidgets.QPushButton(self.widget_8)
        self.stop_button.setStyleSheet("image: url(./Pictures/stop.png);\n"
"border: 0px;")
        self.stop_button.setText("")
        self.stop_button.setObjectName("stop_button")
        self.verticalLayout_5.addWidget(self.stop_button)
        self.horizontalLayout_7.addWidget(self.widget_8)
        self.openWav_button = QtWidgets.QPushButton(self.widget_3)
        self.openWav_button.setMinimumSize(QtCore.QSize(50, 50))
        self.openWav_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.openWav_button.setStyleSheet("image: url(./Pictures/wav.png);\n"
"border: 0px;")
        self.openWav_button.setText("")
        self.openWav_button.setObjectName("openWav_button")
        self.horizontalLayout_7.addWidget(self.openWav_button)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_11 = QtWidgets.QWidget(self.widget)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ASML_logo = QtWidgets.QLabel(self.widget_11)
        self.ASML_logo.setMinimumSize(QtCore.QSize(50, 50))
        self.ASML_logo.setStyleSheet("image: url(./Pictures/asml.png);\n"
"border: 0px;")
        self.ASML_logo.setText("")
        self.ASML_logo.setObjectName("ASML_logo")
        self.horizontalLayout_2.addWidget(self.ASML_logo)
        self.KT_logo = QtWidgets.QLabel(self.widget_11)
        self.KT_logo.setMinimumSize(QtCore.QSize(50, 50))
        self.KT_logo.setStyleSheet("image: url(./Pictures/kt.png);\n"
"border: 0px;")
        self.KT_logo.setText("")
        self.KT_logo.setObjectName("KT_logo")
        self.horizontalLayout_2.addWidget(self.KT_logo)
        self.verticalLayout_7.addWidget(self.widget_11)
        self.widget_10 = QtWidgets.QWidget(self.widget)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.HY_logo = QtWidgets.QLabel(self.widget_10)
        self.HY_logo.setMinimumSize(QtCore.QSize(0, 70))
        self.HY_logo.setStyleSheet("image: url(./Pictures/hy.png);\n"
"border: 0px;")
        self.HY_logo.setText("")
        self.HY_logo.setObjectName("HY_logo")
        self.horizontalLayout_8.addWidget(self.HY_logo)
        self.verticalLayout_7.addWidget(self.widget_10)
        self.verticalLayout_4.addWidget(self.widget)
        self.horizontalLayout_6.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.bottom_Widget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        KT.setCentralWidget(self.centralwidget)

        self.retranslateUi(KT)
        QtCore.QMetaObject.connectSlotsByName(KT)

    def retranslateUi(self, KT):
        _translate = QtCore.QCoreApplication.translate
        KT.setWindowTitle(_translate("KT", "KT End-to-End Project"))
        self.Original_Script.setText(_translate("KT", "Original Script"))
        self.Kaldi_Script.setText(_translate("KT", "Kaldi Script"))
        self.E2E_Script.setText(_translate("KT", "End-to-End Script"))
        self.WER_Label.setText(_translate("KT", "WER(%)"))
        self.CER_Label.setText(_translate("KT", "CER(%)"))
        self.Kaldi_WER.setText(_translate("KT", "-"))
        self.Kaldi_CER.setText(_translate("KT", "-"))
        self.E2E_WER.setText(_translate("KT", "-"))
        self.E2E_CER.setText(_translate("KT", "-"))
        self.FileName_label.setText(_translate("KT", "Filename"))

