# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KT_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_KT(object):
    def setupUi(self, KT):
        KT.setObjectName("KT")
        KT.resize(966, 826)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(KT.sizePolicy().hasHeightForWidth())
        KT.setSizePolicy(sizePolicy)
        KT.setStyleSheet("background-color: rgb(47,48,51)")
        self.centralwidget = QtWidgets.QWidget(KT)
        self.centralwidget.setStyleSheet("background-color: rgb(47,48,51);\n"
"font: 10pt \"Malgun Gothic\";s")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Widget = QtWidgets.QWidget(self.centralwidget)
        self.Top_Widget.setStyleSheet("background-color: rgb(191,191,191);\n"
"font: 10pt \"Malgun Gothic\";")
        self.Top_Widget.setObjectName("Top_Widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.Top_Widget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.TopLeft_Widget = QtWidgets.QWidget(self.Top_Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopLeft_Widget.sizePolicy().hasHeightForWidth())
        self.TopLeft_Widget.setSizePolicy(sizePolicy)
        self.TopLeft_Widget.setMinimumSize(QtCore.QSize(590, 0))
        self.TopLeft_Widget.setStyleSheet("")
        self.TopLeft_Widget.setObjectName("TopLeft_Widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.TopLeft_Widget)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.TopLeft_Widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Original_title = QtWidgets.QLabel(self.widget_3)
        self.Original_title.setMinimumSize(QtCore.QSize(103, 74))
        self.Original_title.setMaximumSize(QtCore.QSize(103, 16777215))
        self.Original_title.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.Original_title.setAlignment(QtCore.Qt.AlignCenter)
        self.Original_title.setObjectName("Original_title")
        self.horizontalLayout_7.addWidget(self.Original_title)
        self.Original_Script = QtWidgets.QLabel(self.widget_3)
        self.Original_Script.setMinimumSize(QtCore.QSize(630, 74))
        self.Original_Script.setMaximumSize(QtCore.QSize(16777215, 78))
        self.Original_Script.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.Original_Script.setAlignment(QtCore.Qt.AlignCenter)
        self.Original_Script.setObjectName("Original_Script")
        self.horizontalLayout_7.addWidget(self.Original_Script)
        self.WER_Label = QtWidgets.QLabel(self.widget_3)
        self.WER_Label.setMinimumSize(QtCore.QSize(60, 74))
        self.WER_Label.setMaximumSize(QtCore.QSize(55, 77))
        self.WER_Label.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.WER_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.WER_Label.setObjectName("WER_Label")
        self.horizontalLayout_7.addWidget(self.WER_Label)
        self.CER_Label = QtWidgets.QLabel(self.widget_3)
        self.CER_Label.setMinimumSize(QtCore.QSize(60, 74))
        self.CER_Label.setMaximumSize(QtCore.QSize(55, 77))
        self.CER_Label.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.CER_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.CER_Label.setObjectName("CER_Label")
        self.horizontalLayout_7.addWidget(self.CER_Label)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(self.TopLeft_Widget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Kaldi_title = QtWidgets.QLabel(self.widget_5)
        self.Kaldi_title.setMinimumSize(QtCore.QSize(103, 74))
        self.Kaldi_title.setMaximumSize(QtCore.QSize(103, 16777215))
        self.Kaldi_title.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.Kaldi_title.setAlignment(QtCore.Qt.AlignCenter)
        self.Kaldi_title.setObjectName("Kaldi_title")
        self.horizontalLayout_10.addWidget(self.Kaldi_title)
        self.Kaldi_Script = QtWidgets.QLabel(self.widget_5)
        self.Kaldi_Script.setMinimumSize(QtCore.QSize(630, 77))
        self.Kaldi_Script.setMaximumSize(QtCore.QSize(16777215, 77))
        self.Kaldi_Script.setToolTipDuration(-1)
        self.Kaldi_Script.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.Kaldi_Script.setAlignment(QtCore.Qt.AlignCenter)
        self.Kaldi_Script.setObjectName("Kaldi_Script")
        self.horizontalLayout_10.addWidget(self.Kaldi_Script)
        self.Kaldi_WER = QtWidgets.QLabel(self.widget_5)
        self.Kaldi_WER.setMinimumSize(QtCore.QSize(60, 74))
        self.Kaldi_WER.setMaximumSize(QtCore.QSize(55, 77))
        self.Kaldi_WER.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.Kaldi_WER.setAlignment(QtCore.Qt.AlignCenter)
        self.Kaldi_WER.setObjectName("Kaldi_WER")
        self.horizontalLayout_10.addWidget(self.Kaldi_WER)
        self.Kaldi_CER = QtWidgets.QLabel(self.widget_5)
        self.Kaldi_CER.setMinimumSize(QtCore.QSize(60, 74))
        self.Kaldi_CER.setMaximumSize(QtCore.QSize(55, 77))
        self.Kaldi_CER.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.Kaldi_CER.setAlignment(QtCore.Qt.AlignCenter)
        self.Kaldi_CER.setObjectName("Kaldi_CER")
        self.horizontalLayout_10.addWidget(self.Kaldi_CER)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_8 = QtWidgets.QWidget(self.TopLeft_Widget)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.E2E_title = QtWidgets.QLabel(self.widget_8)
        self.E2E_title.setMinimumSize(QtCore.QSize(103, 74))
        self.E2E_title.setMaximumSize(QtCore.QSize(103, 16777215))
        self.E2E_title.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.E2E_title.setAlignment(QtCore.Qt.AlignCenter)
        self.E2E_title.setObjectName("E2E_title")
        self.horizontalLayout_11.addWidget(self.E2E_title)
        self.E2E_Script = QtWidgets.QLabel(self.widget_8)
        self.E2E_Script.setMinimumSize(QtCore.QSize(630, 78))
        self.E2E_Script.setMaximumSize(QtCore.QSize(16777215, 78))
        self.E2E_Script.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.E2E_Script.setAlignment(QtCore.Qt.AlignCenter)
        self.E2E_Script.setObjectName("E2E_Script")
        self.horizontalLayout_11.addWidget(self.E2E_Script)
        self.E2E_WER = QtWidgets.QLabel(self.widget_8)
        self.E2E_WER.setMinimumSize(QtCore.QSize(60, 56))
        self.E2E_WER.setMaximumSize(QtCore.QSize(55, 77))
        self.E2E_WER.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.E2E_WER.setAlignment(QtCore.Qt.AlignCenter)
        self.E2E_WER.setObjectName("E2E_WER")
        self.horizontalLayout_11.addWidget(self.E2E_WER)
        self.E2E_CER = QtWidgets.QLabel(self.widget_8)
        self.E2E_CER.setMinimumSize(QtCore.QSize(60, 56))
        self.E2E_CER.setMaximumSize(QtCore.QSize(55, 77))
        self.E2E_CER.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.E2E_CER.setAlignment(QtCore.Qt.AlignCenter)
        self.E2E_CER.setObjectName("E2E_CER")
        self.horizontalLayout_11.addWidget(self.E2E_CER)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.horizontalLayout_9.addWidget(self.TopLeft_Widget)
        self.verticalLayout.addWidget(self.Top_Widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bottom_Widget = QtWidgets.QWidget(self.centralwidget)
        self.bottom_Widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bottom_Widget.setStyleSheet("background-color: rgb(191,191,191);\n"
"font: 10pt \"Malgun Gothic\";")
        self.bottom_Widget.setObjectName("bottom_Widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.bottom_Widget)
        self.horizontalLayout_6.setContentsMargins(20, 7, -1, 18)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_9 = QtWidgets.QWidget(self.bottom_Widget)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_6.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.FileName_label = QtWidgets.QLabel(self.widget_9)
        self.FileName_label.setMinimumSize(QtCore.QSize(500, 40))
        self.FileName_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.FileName_label.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.FileName_label.setLineWidth(8)
        self.FileName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.FileName_label.setObjectName("FileName_label")
        self.verticalLayout_6.addWidget(self.FileName_label)
        self.Wav_Widget = QtWidgets.QWidget(self.widget_9)
        self.Wav_Widget.setMinimumSize(QtCore.QSize(500, 210))
        self.Wav_Widget.setMaximumSize(QtCore.QSize(16777215, 400))
        self.Wav_Widget.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.Wav_Widget.setObjectName("Wav_Widget")
        self.verticalLayout_6.addWidget(self.Wav_Widget)
        self.widget_4 = QtWidgets.QWidget(self.widget_9)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Kaldi_label = QtWidgets.QLabel(self.widget_6)
        self.Kaldi_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Kaldi_label.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.Kaldi_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Kaldi_label.setObjectName("Kaldi_label")
        self.verticalLayout_3.addWidget(self.Kaldi_label)
        self.widget_11 = QtWidgets.QWidget(self.widget_6)
        self.widget_11.setMinimumSize(QtCore.QSize(220, 69))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 69))
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Kaldi_play_button = QtWidgets.QPushButton(self.widget_11)
        self.Kaldi_play_button.setMinimumSize(QtCore.QSize(0, 35))
        self.Kaldi_play_button.setMaximumSize(QtCore.QSize(60, 60))
        self.Kaldi_play_button.setStyleSheet("image: url(./Pictures/play.png);\n"
"border: 0px;")
        self.Kaldi_play_button.setText("")
        self.Kaldi_play_button.setObjectName("Kaldi_play_button")
        self.horizontalLayout_2.addWidget(self.Kaldi_play_button)
        self.Kaldi_stop_button = QtWidgets.QPushButton(self.widget_11)
        self.Kaldi_stop_button.setMinimumSize(QtCore.QSize(0, 35))
        self.Kaldi_stop_button.setMaximumSize(QtCore.QSize(60, 60))
        self.Kaldi_stop_button.setStyleSheet("image: url(./Pictures/stop.png);\n"
"border: 0px;")
        self.Kaldi_stop_button.setText("")
        self.Kaldi_stop_button.setObjectName("Kaldi_stop_button")
        self.horizontalLayout_2.addWidget(self.Kaldi_stop_button)
        self.verticalLayout_3.addWidget(self.widget_11)
        self.Kaldi_Decoding_label = QtWidgets.QLabel(self.widget_6)
        self.Kaldi_Decoding_label.setMinimumSize(QtCore.QSize(220, 20))
        self.Kaldi_Decoding_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Kaldi_Decoding_label.setText("")
        self.Kaldi_Decoding_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Kaldi_Decoding_label.setObjectName("Kaldi_Decoding_label")
        self.verticalLayout_3.addWidget(self.Kaldi_Decoding_label)
        self.horizontalLayout_3.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.E2E_label = QtWidgets.QLabel(self.widget_7)
        self.E2E_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.E2E_label.setStyleSheet("border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.E2E_label.setAlignment(QtCore.Qt.AlignCenter)
        self.E2E_label.setObjectName("E2E_label")
        self.verticalLayout_5.addWidget(self.E2E_label)
        self.widget_14 = QtWidgets.QWidget(self.widget_7)
        self.widget_14.setMinimumSize(QtCore.QSize(220, 69))
        self.widget_14.setMaximumSize(QtCore.QSize(16777215, 69))
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.E2E_play_button = QtWidgets.QPushButton(self.widget_14)
        self.E2E_play_button.setMinimumSize(QtCore.QSize(0, 35))
        self.E2E_play_button.setMaximumSize(QtCore.QSize(60, 60))
        self.E2E_play_button.setStyleSheet("image: url(./Pictures/play.png);\n"
"border: 0px;")
        self.E2E_play_button.setText("")
        self.E2E_play_button.setObjectName("E2E_play_button")
        self.horizontalLayout_4.addWidget(self.E2E_play_button)
        self.E2E_stop_button = QtWidgets.QPushButton(self.widget_14)
        self.E2E_stop_button.setMinimumSize(QtCore.QSize(0, 35))
        self.E2E_stop_button.setMaximumSize(QtCore.QSize(60, 60))
        self.E2E_stop_button.setStyleSheet("image: url(./Pictures/stop.png);\n"
"border: 0px;")
        self.E2E_stop_button.setText("")
        self.E2E_stop_button.setObjectName("E2E_stop_button")
        self.horizontalLayout_4.addWidget(self.E2E_stop_button)
        self.verticalLayout_5.addWidget(self.widget_14)
        self.E2E_Decoding_label = QtWidgets.QLabel(self.widget_7)
        self.E2E_Decoding_label.setMinimumSize(QtCore.QSize(220, 20))
        self.E2E_Decoding_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.E2E_Decoding_label.setText("")
        self.E2E_Decoding_label.setAlignment(QtCore.Qt.AlignCenter)
        self.E2E_Decoding_label.setObjectName("E2E_Decoding_label")
        self.verticalLayout_5.addWidget(self.E2E_Decoding_label)
        self.horizontalLayout_3.addWidget(self.widget_7)
        self.verticalLayout_6.addWidget(self.widget_4)
        self.widget_12 = QtWidgets.QWidget(self.widget_9)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_6.addWidget(self.widget_12)
        self.horizontalLayout_6.addWidget(self.widget_9)
        self.widget_2 = QtWidgets.QWidget(self.bottom_Widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.FileList = QtWidgets.QListView(self.widget_2)
        self.FileList.setMinimumSize(QtCore.QSize(375, 311))
        self.FileList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.FileList.setStyleSheet("background-color: rgb(255,255,255);border-left: 1px solid rgb(77, 77, 77);border-right: 1px solid rgb(77, 77, 77);border-top: 1px solid rgb(77, 77, 77);border-bottom: 1px solid rgb(77, 77, 77);")
        self.FileList.setObjectName("FileList")
        self.verticalLayout_4.addWidget(self.FileList)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_10 = QtWidgets.QWidget(self.widget)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.HY_logo = QtWidgets.QLabel(self.widget_10)
        self.HY_logo.setMinimumSize(QtCore.QSize(168, 110))
        self.HY_logo.setMaximumSize(QtCore.QSize(168, 110))
        self.HY_logo.setStyleSheet("image: url(./Pictures/hy.png);\n"
"border: 0px;")
        self.HY_logo.setText("")
        self.HY_logo.setObjectName("HY_logo")
        self.horizontalLayout_8.addWidget(self.HY_logo)
        self.KT_logo = QtWidgets.QLabel(self.widget_10)
        self.KT_logo.setMinimumSize(QtCore.QSize(81, 45))
        self.KT_logo.setMaximumSize(QtCore.QSize(81, 45))
        self.KT_logo.setStyleSheet("image: url(./Pictures/kt.png);\n"
"border: 0px;")
        self.KT_logo.setText("")
        self.KT_logo.setObjectName("KT_logo")
        self.horizontalLayout_8.addWidget(self.KT_logo)
        self.verticalLayout_7.addWidget(self.widget_10)
        self.verticalLayout_4.addWidget(self.widget)
        self.horizontalLayout_6.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.bottom_Widget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        KT.setCentralWidget(self.centralwidget)

        self.retranslateUi(KT)
        QtCore.QMetaObject.connectSlotsByName(KT)

    def retranslateUi(self, KT):
        _translate = QtCore.QCoreApplication.translate
        KT.setWindowTitle(_translate("KT", "KT End-to-End Project"))
        self.Original_title.setText(_translate("KT", "Original"))
        self.Original_Script.setText(_translate("KT", "Original Script"))
        self.WER_Label.setText(_translate("KT", "WER(%)"))
        self.CER_Label.setText(_translate("KT", "CER(%)"))
        self.Kaldi_title.setText(_translate("KT", "<html><head/><body><p>Johns Hopkins<br/>Univ</p><p>(Kaldi)</p></body></html>"))
        self.Kaldi_Script.setText(_translate("KT", "Kaldi Script"))
        self.Kaldi_WER.setText(_translate("KT", "-"))
        self.Kaldi_CER.setText(_translate("KT", "-"))
        self.E2E_title.setText(_translate("KT", "<html><head/><body><p>Hanyang Univ</p><p>(End-to-End)</p></body></html>"))
        self.E2E_Script.setText(_translate("KT", "End-to-End Script"))
        self.E2E_WER.setText(_translate("KT", "-"))
        self.E2E_CER.setText(_translate("KT", "-"))
        self.FileName_label.setText(_translate("KT", "Filename"))
        self.Kaldi_label.setText(_translate("KT", "Kaldi"))
        self.E2E_label.setText(_translate("KT", "End-to-End"))

