model_file: latest.pth

dataset: cifar10
in_ch: 3
out_ch: 10
batch_size: 600

xai_excute: 1
xai_mode: gxsi
xai_iter: 3

bias: 0
batch_norm: 1
cfg_type: nib_D

plot_flag: 1

st_excute: 1
teacher_cfg_type: nib_B2
teacher_model_path: exp/imgr_train_vgg7_bnwob/latest.pth