dataset: cifar100
in_ch: 3
out_ch: 100

accum_grad: 1
max_epoch: 200
batch_size: 1000

best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

scheduler: steplr
scheduler_conf:
    step_size: 60
    gamma: 0.2

optim: sgd
optim_conf:
    lr: 0.1
    weight_decay: 0.0005
    momentum: 0.9

xai_excute: 1
xai_mode: bg
xai_iter: 3
st_excute: 0

bias: 0
batch_norm: 0
cfg_type: D

