dataset: cifar10
in_ch: 3
out_ch: 10

accum_grad: 1
max_epoch: 70
batch_size: 88

best_model_criterion:
-   - valid
    - acc_iter0
    - max
keep_nbest_models: 1

scheduler: multisteplr
scheduler_conf:
    milestones:
        - 60
    gamma: 0.1

optim: sgd
optim_conf:
    lr: 0.1
    weight_decay: 0.0005
    momentum: 0.9

xai_excute: 1
xai_mode: gxsi
xai_iter: 3

bias: 0
batch_norm: 1
cfg_type: nib_D

st_excute: 1
teacher_cfg_type: nib_B2
teacher_model_path: exp/imgr_train_vgg7_bnwob/latest.pth