dataset: cifar100
in_ch: 3
out_ch: 100

accum_grad: 1
max_epoch: 175
batch_size: 22

best_model_criterion:
-   - valid
    - acc_iter0
    - max
keep_nbest_models: 1

scheduler: multisteplr
scheduler_conf:
    milestones:
        - 100
        - 150
    gamma: 0.1

optim: sgd
optim_conf:
    lr: 0.1
    weight_decay: 0.0005
    momentum: 0.9

xai_excute: 1
xai_mode: bg
xai_iter: 20
st_excute: 0

bias: 0
batch_norm: 1
cfg_type: D