dataset: cifar100
in_ch: 3
out_ch: 100

accum_grad: 1
max_epoch: 100
batch_size: 128

best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

scheduler: steplr
scheduler_conf:
    step_size: 60
    gamma: 0.2

optim: sgd
optim_conf:
    lr: 0.1
    weight_decay: 0.0005
    momentum: 0.9

xai_excute: 0
xai_mode: bg
st_excute: 0

bias: 1
batch_norm: 1
cfg_type: D

